name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Commits ahead/behind'
    required: true
  branch-name:
    description: 'Name of feature branch'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commit-diff }}
    - ${{ inputs.branch-name }}
